# Generated by Django 4.1.7 on 2023-04-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='media/')),
            ],
        ),
    ]
