# Generated by Django 4.1.7 on 2023-04-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_seller', '0003_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=250)),
                ('image', models.FileField(default='ghughu', upload_to='pimage/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_seller.seller_user')),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
